<a href="https://colab.research.google.com/github/ene23033/repository/blob/master/NASA_Solcast_WS_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [4]:
df1=pd.read_csv('/content/NASA(24-01-24 to 27-01-25)one hr.csv')
df1.index=pd.to_datetime(df1['timestamp'], format= '%d-%m-%Y %H:%M')
df1.head()

,timestamp,T2M,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
timestamp,,,,,,,,,,
2024-12-24 01:00:00,24-12-2024 01:00,18.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-24 02:00:00,24-12-2024 02:00,18.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-24 03:00:00,24-12-2024 03:00,18.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-24 04:00:00,24-12-2024 04:00,17.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-24 05:00:00,24-12-2024 05:00,17.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2 = pd.read_csv('/content/weatherstationIITB(24-01-24 to 30-01-25) one min.csv')
df2.index = pd.to_datetime(df2['TIMESTAMP'], format='%d-%m-%Y %H:%M')
df2.head()

,TIMESTAMP,RECORD,SlrFD_W_Avg,Rain_mm_Tot,Strikes_Tot,Dist_km_Avg,WS_ms_Avg,WindDir,MaxWS_ms_Avg,AirT_C_Avg,VP_kPa_Avg,BP_kPa_Avg,RH,RHT_C_Avg,TiltNS_deg_Avg,TiltWE_deg_Avg,SlrTF_MJ_Tot,CVMeta,Invalid_Wind_Avg
TIMESTAMP,,,,,,,,,,,,,,,,,,,
2024-12-24 11:00:00,24-12-2024 11:00,0,423.8,0,0,0,0.798,341.7,0.892,21.27,1.676667,83.75833,61.6,23.68,1.417,-0.083,0.007630,NaN,0
2024-12-24 11:01:00,24-12-2024 11:01,1,504.3,0,0,0,1.395,101.6,1.395,25.58,2.015000,100.51000,59.9,28.48,1.525,-0.075,0.015100,NaN,0
2024-12-24 11:02:00,24-12-2024 11:02,2,493.1,0,0,0,0.936,355.8,0.936,25.65,2.015833,100.50830,61.9,28.54,-1664.000,-1665.000,0.014765,NaN,0
2024-12-24 11:03:00,24-12-2024 11:03,3,491.1,0,0,0,1.205,17.0,1.205,25.68,2.022500,100.51000,62.5,28.56,1.642,-0.033,0.014760,NaN,0
2024-12-24 11:04:00,24-12-2024 11:04,4,504.0,0,0,0,1.858,7.1,1.858,25.33,2.012500,100.51000,61.9,28.61,1.592,0.267,0.015135,NaN,0

In [7]:
df3 = pd.merge(df1, df2, left_on=df1.index, right_on=df2.index, how='inner')

df3.to_csv('AirT_Merged_file(NASA-WS).csv', index=False)

df3.head()

,key_0,timestamp,T2M,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,AirT_C_Avg,VP_kPa_Avg,BP_kPa_Avg,RH,RHT_C_Avg,TiltNS_deg_Avg,TiltWE_deg_Avg,SlrTF_MJ_Tot,CVMeta,Invalid_Wind_Avg
0,2024-12-24 11:00:00,24-12-2024 11:00,27.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.27,1.676667,83.75833,61.6,23.68,1.417,-0.083,0.007630,NaN,0
1,2024-12-24 12:00:00,24-12-2024 12:00,28.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.44,2.072500,100.42000,56.9,30.57,-1663.000,-1665.000,0.018045,NaN,0
2,2024-12-24 13:00:00,24-12-2024 13:00,28.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.23,2.092500,100.30420,58.5,30.97,1.625,-0.117,0.017270,NaN,0
3,2024-12-24 14:00:00,24-12-2024 14:00,27.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.34,2.042500,100.23000,54.9,30.37,1.800,0.200,0.013990,NaN,0
4,2024-12-24 15:00:00,24-12-2024 15:00,26.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.46,1.993333,100.16170,53.7,30.88,1.642,0.333,0.011740,NaN,0

In [8]:
df4=pd.read_csv('/content/Solcast_air_temp(24-01-24 to 27-01-25) one hr.csv')

In [9]:
df4.head()

   air_temp         timestamp
0      22.0  24-12-2024 01:00
1      21.0  24-12-2024 02:00
2      21.0  24-12-2024 03:00
3      21.0  24-12-2024 04:00
4      22.0  24-12-2024 05:00

In [10]:
df4.index=pd.to_datetime(df4['timestamp'],format='%d-%m-%Y %H:%M')
df4.head()

                     air_temp         timestamp
timestamp
2024-12-24 01:00:00      22.0  24-12-2024 01:00
2024-12-24 02:00:00      21.0  24-12-2024 02:00
2024-12-24 03:00:00      21.0  24-12-2024 03:00
2024-12-24 04:00:00      21.0  24-12-2024 04:00
2024-12-24 05:00:00      22.0  24-12-2024 05:00

In [11]:
df5=pd.read_csv('/content/AirT_Merged_file(NASA-WS).csv')
df5.head()

          timestamp  NASA_Temp  Station_Temp
0  24-12-2024 11:00      27.29         21.27
1  24-12-2024 12:00      28.05         27.44
2  24-12-2024 13:00      28.14         27.23
3  24-12-2024 14:00      27.51         27.34
4  24-12-2024 15:00      26.63         27.46

In [12]:
df5.index=pd.to_datetime(df5['timestamp'],format='%d-%m-%Y %H:%M')
df5.head()

                            timestamp  NASA_Temp  Station_Temp
timestamp
2024-12-24 11:00:00  24-12-2024 11:00      27.29         21.27
2024-12-24 12:00:00  24-12-2024 12:00      28.05         27.44
2024-12-24 13:00:00  24-12-2024 13:00      28.14         27.23
2024-12-24 14:00:00  24-12-2024 14:00      27.51         27.34
2024-12-24 15:00:00  24-12-2024 15:00      26.63         27.46

In [13]:
df6=pd.merge(df4,df5,left_on=df4.index,right_on=df5.index,how='inner')
df6.to_csv('Merged_NASA_Sol_WS.csv', index=False)
df6.head()

,key_0,air_temp,timestamp_x,timestamp_y,NASA_Temp,Station_Temp
0,2024-12-24 11:00:00,25.0,24-12-2024 11:00,24-12-2024 11:00,27.29,21.27
1,2024-12-24 12:00:00,26.0,24-12-2024 12:00,24-12-2024 12:00,28.05,27.44
2,2024-12-24 13:00:00,27.0,24-12-2024 13:00,24-12-2024 13:00,28.14,27.23
3,2024-12-24 14:00:00,27.0,24-12-2024 14:00,24-12-2024 14:00,27.51,27.34
4,2024-12-24 15:00:00,26.0,24-12-2024 15:00,24-12-2024 15:00,26.63,27.46